Implementations by JH
bytabo/node-boilerplate pull request #1
Opened 2021-02-10 12:40 UTC by bytabo

2021-03-01 11:41 UTC, danim87 requested changes

2021-03-01 11:41 UTC, danim87 commented on modules/middleware.module.js
> +const middleware = {};
ich versteh hier den Ausdruck middleware nicht so recht - das ist ja einfach nur fuer security oder?

2021-03-01 11:41 UTC, danim87 commented on modules/mailer.module.js
> +const nodemailer = require('nodemailer');
ich wuerde dieses Konstrukt hier eher als service sehen um mails zu senden, ich denke wir werden uns fuer modules oder services entscheiden muessen...ich waere dann fuer services mit factories

2021-03-01 11:41 UTC, danim87 commented on app.js
> +// todo: swagger, error handling, logging, concurrency (performance), editorconfig (brauchen wir gar nicht oder?!), cronjobs module?
die ToDos wuerde ich in die README setzen, was wir noch verbauen wollen (editorconfig kann gerne rein)
Bitte kein Deutsch im code verwenden :)

2021-03-01 11:41 UTC, danim87 commented on README.md
> +* SMTP_HOST= ```SMTP SERVER eg. ux234234.all-inkl.com```
eg wuerde ich weglassen hier - ist ja klar

2021-03-01 11:42 UTC, danim87 commented on README.md
> +* SMTP_HOST= ```SMTP SERVER eg. ux234234.all-inkl.com```
also ich meine das Beispiel weglassen

2021-03-01 11:43 UTC, danim87 commented
bitte das nexte Mal nach Standard mit feature branches arbeiten und diese reviewen auf dem develop - auf master dann danach schieben bitte

2021-03-08 12:47 UTC, johoehn commented on README.md
> +* SMTP_HOST= ```SMTP SERVER eg. ux234234.all-inkl.com```
done

2021-03-11 14:09 UTC, danim87 approved these changes

2021-03-12 09:17 UTC, danim87 requested changes

2021-03-12 09:17 UTC, danim87 commented on README.md
> +* Logging (eg bunyan or winston)
we got that now right? :)

2021-03-12 09:17 UTC, danim87 commented on services/cronjobs.factory.js
> +const factory = require('./cronjobs.service')({ cron, logger });
I wld name that cronJobService , cause u exporting the service and not the factory :)

2021-03-12 09:17 UTC, danim87 commented on services/cronjobs.service.js
> +    // every moth
ur typo is still here muhaha :)

2021-03-12 09:17 UTC, danim87 commented on services/json.factory.js
> +const factory = require('./json.service')({ axios });
same here naming -> jsonService eg

2021-03-12 09:17 UTC, danim87 commented on services/logger.factory.js
> +const factory = require('./logger.service')({ winston });
same here naming

2021-03-12 09:17 UTC, danim87 commented on services/logger.service.js
> +    // add output also to console on development
u cld outsource the things that are in the if and else into funcs then u dont need a comment to explain - ur funcs in if and else wld explain what they do :)

2021-03-12 09:17 UTC, danim87 commented on services/mailer.factory.js
> +const factory = require('./mailer.service')({ nodemailer, ejs });
naming here same

2021-03-12 10:43 UTC, merged